package humanlayout

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/alexsmedile/spectacular/v2/internal/discovery"
	"github.com/alexsmedile/spectacular/v2/internal/domain"
	"github.com/alexsmedile/spectacular/v2/internal/workspace"
)

type indexRow struct {
	Ref   string
	Noun  string
	Title string
	Path  string
}

// Indexes returns deterministic non-authoritative Markdown projections for
// the root, affected collections, and affected Mission bundles.
func Indexes(existing []discovery.Entry, pending []*workspace.Document, paths map[domain.ID]string) (map[string][]byte, error) {
	pendingIDs := map[domain.ID]bool{}
	rows := make([]indexRow, 0, len(existing)+len(pending))
	for _, doc := range pending {
		pendingIDs[doc.Record.ID] = true
	}
	for _, entry := range existing {
		if pendingIDs[entry.Document.Record.ID] {
			continue
		}
		rows = append(rows, row(entry.Document, entry.Path))
	}
	for _, doc := range pending {
		path := paths[doc.Record.ID]
		if path == "" {
			return nil, fmt.Errorf("missing planned path for %s", doc.Record.ID)
		}
		rows = append(rows, row(doc, path))
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].Ref == rows[j].Ref {
			return rows[i].Path < rows[j].Path
		}
		return rows[i].Ref < rows[j].Ref
	})

	groups := map[string][]indexRow{".spectacular/index.md": rows}
	for _, item := range rows {
		parts := strings.Split(filepath.ToSlash(item.Path), "/")
		if len(parts) < 3 || parts[0] != ".spectacular" {
			continue
		}
		top := parts[1]
		if top == "PROJECT.md" || top == "PRODUCT.md" || top == "ARCHITECTURE.md" || top == "STACK.md" {
			continue
		}
		groups[filepath.ToSlash(filepath.Join(".spectacular", top, "index.md"))] = append(groups[filepath.ToSlash(filepath.Join(".spectacular", top, "index.md"))], item)
		if (top == "missions" || top == "archive") && len(parts) >= 4 {
			bundleIndex := ""
			if top == "missions" {
				bundleIndex = filepath.ToSlash(filepath.Join(".spectacular", "missions", parts[2], "index.md"))
			} else if len(parts) >= 5 && parts[2] == "missions" {
				bundleIndex = filepath.ToSlash(filepath.Join(".spectacular", "archive", "missions", parts[3], "index.md"))
			}
			if bundleIndex != "" {
				groups[bundleIndex] = append(groups[bundleIndex], item)
			}
		}
	}

	out := map[string][]byte{}
	for path, items := range groups {
		sort.Slice(items, func(i, j int) bool { return items[i].Ref < items[j].Ref })
		var text strings.Builder
		text.WriteString("<!-- generated by Spectacular; non-authoritative; do not edit -->\n")
		text.WriteString("# Workspace index\n\n")
		text.WriteString("| Ref | Type | Title | Source |\n|---|---|---|---|\n")
		for _, item := range items {
			fmt.Fprintf(&text, "| `%s` | %s | %s | `%s` |\n", item.Ref, item.Noun, escapeCell(item.Title), item.Path)
		}
		out[path] = []byte(text.String())
	}
	return out, nil
}

func row(doc *workspace.Document, path string) indexRow {
	ref := HumanRef(doc)
	if ref == "" {
		ref = string(doc.Record.Type) + ":" + doc.Record.ID.String()
	}
	title := ""
	if doc.Record.Title != nil {
		title = *doc.Record.Title
	}
	return indexRow{Ref: ref, Noun: string(doc.Record.Type), Title: title, Path: filepath.ToSlash(path)}
}

func escapeCell(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "|", "\\|"), "\n", " ")
}
