package humanlayout

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/alexsmedile/spectacular/v2/internal/discovery"
	"github.com/alexsmedile/spectacular/v2/internal/domain"
	"github.com/alexsmedile/spectacular/v2/internal/workspace"
)

type indexRow struct {
	Ref    string
	Noun   string
	Title  string
	Path   string
	Status string
}

// Indexes returns deterministic non-authoritative Markdown projections for
// the root and affected collections. The root Mission record is the Mission-bundle index;
// generating another index inside every Mission would duplicate it.
func Indexes(existing []discovery.Entry, pending []*workspace.Document, paths map[domain.ID]string) (map[string][]byte, error) {
	pendingIDs := map[domain.ID]bool{}
	touchedCollections := map[string]bool{}
	rows := make([]indexRow, 0, len(existing)+len(pending))
	for _, doc := range pending {
		pendingIDs[doc.Record.ID] = true
	}
	for _, entry := range existing {
		if pendingIDs[entry.Document.Record.ID] {
			if index := collectionIndex(entry.Path); index != "" {
				touchedCollections[index] = true
			}
			continue
		}
		rows = append(rows, row(entry.Document, entry.Path))
	}
	for _, doc := range pending {
		path := paths[doc.Record.ID]
		if path == "" {
			return nil, fmt.Errorf("missing planned path for %s", doc.Record.ID)
		}
		rows = append(rows, row(doc, path))
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].Ref == rows[j].Ref {
			return rows[i].Path < rows[j].Path
		}
		return rows[i].Ref < rows[j].Ref
	})

	groups := map[string][]indexRow{".spectacular/catalog.md": rows}
	for path := range touchedCollections {
		groups[path] = []indexRow{}
	}
	for _, item := range rows {
		parts := strings.Split(filepath.ToSlash(item.Path), "/")
		if len(parts) < 3 || parts[0] != ".spectacular" {
			continue
		}
		top := parts[1]
		if top == "PROJECT.md" || top == "PRODUCT.md" || top == "ARCHITECTURE.md" || top == "STACK.md" {
			continue
		}
		if top == "missions" && item.Noun != string(domain.Mission) {
			continue
		}
		if top == "archive" && item.Noun != string(domain.Mission) && item.Noun != string(domain.Proposal) {
			continue
		}
		indexPath := filepath.ToSlash(filepath.Join(".spectacular", top, "index.md"))
		groups[indexPath] = append(groups[indexPath], item)
	}

	out := map[string][]byte{}
	out[".spectacular/index.md"] = workspaceGuide(rows)
	for path, items := range groups {
		sort.Slice(items, func(i, j int) bool { return items[i].Ref < items[j].Ref })
		out[path] = catalog(items, path == ".spectacular/catalog.md")
	}
	return out, nil
}

func collectionIndex(path string) string {
	parts := strings.Split(filepath.ToSlash(path), "/")
	if len(parts) < 3 || parts[0] != ".spectacular" {
		return ""
	}
	switch parts[1] {
	case "PROJECT.md", "PRODUCT.md", "ARCHITECTURE.md", "STACK.md":
		return ""
	default:
		return filepath.ToSlash(filepath.Join(".spectacular", parts[1], "index.md"))
	}
}

func row(doc *workspace.Document, path string) indexRow {
	ref := HumanRef(doc)
	if ref == "" {
		ref = string(doc.Record.Type) + ":" + doc.Record.ID.String()
	} else if !strings.Contains(ref, "/") {
		switch doc.Record.Type {
		case domain.Objective, domain.Run, domain.Review, domain.Evidence, domain.Handoff, domain.Checkpoint:
			if mission, _ := workspace.String(doc, "mission", false); strings.HasPrefix(mission, "M") && !strings.Contains(mission, ":") {
				ref = mission + "/" + ref
			}
		}
	}
	title := ""
	if doc.Record.Title != nil {
		title = *doc.Record.Title
	}
	status := ""
	if doc.Record.Status != nil {
		status = *doc.Record.Status
	}
	return indexRow{Ref: ref, Noun: string(doc.Record.Type), Title: title, Path: filepath.ToSlash(path), Status: status}
}

func workspaceGuide(rows []indexRow) []byte {
	var text strings.Builder
	text.WriteString("<!-- generated by Spectacular; non-authoritative; do not edit -->\n")
	text.WriteString("# Workspace guide\n\n")
	text.WriteString("Compact routing only. Read canonical sources for authority; [catalog.md](catalog.md) is the complete record inventory.\n\n")
	text.WriteString("## Start here\n\n")
	text.WriteString("- [PROJECT.md](PROJECT.md) — accepted direction, boundaries, and current truth.\n")
	text.WriteString("- [campaigns/README.md](campaigns/README.md) — optional strategic roadmap maps.\n")
	text.WriteString("- [missions/index.md](missions/index.md) — Mission discovery.\n")
	text.WriteString("- [proposals/index.md](proposals/index.md) — open explorations.\n\n")
	text.WriteString("## Current work\n\n")
	active := make([]indexRow, 0, 1)
	for _, item := range rows {
		if item.Noun == string(domain.Mission) && item.Status == "active" {
			active = append(active, item)
		}
	}
	if len(active) == 0 {
		text.WriteString("No active Mission is recorded. Prepare a bounded Mission before consequential work.\n")
		return []byte(text.String())
	}
	text.WriteString("| Mission | Outcome | Source |\n|---|---|---|\n")
	for _, item := range active {
		fmt.Fprintf(&text, "| `%s` | %s | `%s` |\n", item.Ref, escapeCell(item.Title), item.Path)
	}
	return []byte(text.String())
}

func catalog(items []indexRow, workspace bool) []byte {
	var text strings.Builder
	text.WriteString("<!-- generated by Spectacular; non-authoritative; do not edit -->\n")
	if workspace {
		text.WriteString("# Workspace catalog\n\n")
		text.WriteString("Complete navigational inventory. Use [index.md](index.md) for compact routing.\n\n")
	} else {
		text.WriteString("# Workspace index\n\n")
	}
	text.WriteString("| Ref | Type | Title | Source |\n|---|---|---|---|\n")
	for _, item := range items {
		fmt.Fprintf(&text, "| `%s` | %s | %s | `%s` |\n", item.Ref, item.Noun, escapeCell(item.Title), item.Path)
	}
	return []byte(text.String())
}

func escapeCell(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "|", "\\|"), "\n", " ")
}
